### PR TITLE
Fix all known Swansong bugs

### PR DESCRIPTION
**Pull request by rl-starbound**
Previous commits to the Starbound Patch Project have introduced fixes for the most game-breaking Swansong bugs. However, the swansong.lua code is still deeply flawed and contains additional movement bugs that can render the fight un-fun, as well as restart the fight in some cases.

I started over with the original code and thoroughly picked the code apart until I found, what I believe, are the root causes of the Swansong bugs. They fall into three main categories:

1. The control approach velocity and force variables can become NaNs, which will ripple throughout the code and cause movement failures. These all appear to be caused by an accidental "square root of a negative number" bug that I've fixed.
1. In the presence of gravity, mcontroller.velocity() will return a non-zero velocity even when an entity is stopped. To reliably determine if an entity is stopped, you must compare previous and current positions. I've fixed this centrally in the `stop` function and rewrite other uses to use it.
1. Swansong can melee dash out of the arena. if this happens, the game will reset the fight from the beginning, which is seriously annoying if the player had nearly destroyed Swansong when it happened.

Additionally, I fixed a few minor issues that I think are bugs, such as the fact that Swansong can kill the player with touch damage during its death throes.

I replaced the world.entityExists checks, even though I don't think they do more than preventing some annoying logging messages. Likewise, I re-added the failsafe timers, even thogh I don't think they're strictly needed anymore; they can't hurt. I have put in some log warnings if the failsafes are invoked, to let us know if this still needs more work.

I've also added comments clarifying what some of the more complex parts of the code do, as well as fixed one glaringly incorrect comment from vanilla code.

With the new swansong.lua code, I've replayed the Swansong fight over 30 times without encountering any bugs, and without seeing any of the failsafe timer warnings in my logs.

### CODE REVIEW

**Comment by rl-starbound** [comment]
I know this fix makes a lot of changes. Let me know if you want me to step you through any of them.

**Comment by jss2a98aj** [comment]
I think velocity issues from gravity was an issue elsewhere, so that bit isn't too surprising. Seems like some good fixes over all. I am hoping to work on the patch project this weekend, so I will be merging and testing this then if I don't have anything unexpected come up.

**Comment by rl-starbound** [comment]
If it's in the Solus Katana, I think I was the one who discovered that. That reminds me, while developing this fix, I developed a better, more general fix for the Solus Katana. If you want I can put that in this patch set, or submit a separate patch.

**Comment by jss2a98aj** [comment]
Separate would probably be better, if it is even needed. I removed its velocity check entirely, as I was still getting it to lock up in some situations. Bar not locking up it didn't behave much differently after.

**Pull request merged**
